# Generated by Django 4.2.30 on 2026-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
